# Generated by Django 3.2.3 on 2021-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='my_pic.jpg', upload_to='about_us')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('establish', models.DateField(blank=True)),
            ],
        ),
    ]
