# Generated by Django 3.2.3 on 2021-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(blank=True, default='profile.svg', upload_to='userprofile'),
        ),
    ]
