# Generated by Django 3.2.3 on 2021-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_writetous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writetous',
            name='user',
        ),
    ]
