# Generated by Django 3.2.3 on 2021-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_advertise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adv_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_start_date',
            field=models.DateField(blank=True),
        ),
    ]
