# Generated by Django 3.1.5 on 2021-06-01 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0010_alter_advertise_adv_datetime_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adv_datetime_now',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 21, 29, 31, 892122)),
        ),
    ]
