# Generated by Django 3.1.5 on 2021-06-01 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0013_auto_20210601_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adv_datetime_now',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 23, 26, 9, 757303)),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_plan',
            field=models.CharField(choices=[(2, 'Free'), (50, 'Weeks'), (150, 'Month')], default='Free', max_length=200),
        ),
    ]
