# Generated by Django 3.2.3 on 2021-06-02 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0014_auto_20210601_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='adv_order_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_datetime_now',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 10, 31, 25, 798013)),
        ),
    ]
