# Generated by Django 3.2.3 on 2021-06-02 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0016_auto_20210602_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_payment',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_datetime_now',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 11, 34, 43, 735982)),
        ),
    ]
