# Generated by Django 3.2.3 on 2021-06-02 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0019_auto_20210602_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_payment',
            name='adv_plan',
            field=models.IntegerField(choices=[(0, 'Free'), (50, 'Weeks'), (150, 'Month')], default='Free', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_datetime_now',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 12, 5, 42, 515860)),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='adv_plan',
            field=models.CharField(choices=[(0, 'Free'), (50, 'Weeks'), (150, 'Month')], default='Free', max_length=200),
        ),
    ]
