# Generated by Django 3.2.3 on 2021-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='again',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
